### ISSUE TITLE
Wrapping a block in a function call

### ISSUE THREAD

**Issue by NightRa** [Peaker/lamdu#10]
Following the factors example from Lamdu's page,
I started writing from inside out, i.e. take, then wrap in filter then wrap in caseList.
In order to wrap the take block in filter, I had to select the whole block (Shift+Left) which wasn't straight forward, and then start writing an operator like +, delete it, and write filter.

At first I expected that if I come behind take and start writing filter it would figure it out, and wrap it.

**Comment by Peaker** [comment]
You just need to press <space> after the Shift+Left.

We intend on implementing a "Gamified Tutorial" to explain things like Shift+Left.

Also, as an alternative to Shift+Left, you can apply the operation (in this case, <space>) to the "representative widget" of the expression (the function name in a "boxed apply", or the close-paren in parenthesis, or the ":" in a case statement, etc..)
