### ISSUE TITLE
OpenGL needs bump to 2.9

### ISSUE THREAD

**Issue by schell** [Peaker/lamdu#13]
I'm running into a compilation error when installing OpenGL 2.8. Bumping the version to 2.9.1 will fix it.

**Comment by Peaker** [comment]
We're using GHC 7.8.3. Can you try building in a sandbox? (First build yairchu's graphics-drawingcombinators fork, or the eyal/more_accurate_fonts branch in luqui's official repo).

**Comment by Peaker** [comment]
This should work fine (we're using GHC 7.10.2 now)
