### ISSUE TITLE
Support for non-QWERTZ layouts

### ISSUE THREAD

**Issue by k00mi** [Peaker/lamdu#15]
GLFW hardcodes the standard US layout, which means that one has to press the physical key associated with the desired character on the American layout, even though it might be a different key on the layout one is actually using.

Only the Key functions do this, the character functions respect the layout.

While this might be desirable behaviour for a game (chat with the layout one is used to, but movement keys stay the same), I don't think it is adequate for an IDE.

A solution by GLFW is planned for 3.1: https://github.com/glfw/glfw/pull/117

**Comment by Peaker** [comment]
Is this still an issue? Can you reopen if so?
