### ISSUE TITLE
Build failure in bottlelib/Data/Cache.hs

### ISSUE THREAD

**Issue by zefram-cochrane** [Peaker/lamdu#19]
I'm using ghc 7.4.1 on ElementaryOS Luna. Did nothing outside the TUTORIAL build instructions except I had to apt-get libXxf86vm to get the GLFW bindings to build. Don't imagine that's implicated in the following:

[56 of 56] Compiling Data.Cache       ( bottlelib/Data/Cache.hs, dist/build/Data/Cache.o )

bottlelib/Data/Cache.hs:119:11:
    Could not deduce (m ~ Lens.Identity)
    from the context (MonadA m, Key k, Typeable v)
      bound by the type signature for
                 lookupS :: (MonadA m, Key k, Typeable v) =>
                            k -> StateT Cache m (Maybe v)
      at bottlelib/Data/Cache.hs:119:1-24
      `m' is a rigid type variable bound by
          the type signature for
            lookupS :: (MonadA m, Key k, Typeable v) =>
                       k -> StateT Cache m (Maybe v)
          at bottlelib/Data/Cache.hs:119:1
    Expected type: (Cache -> (Maybe v, Cache))
                   -> StateT Cache m (Maybe v)
      Actual type: (Cache -> (Maybe v, Cache))
                   -> Control.Monad.Trans.State.Lazy.State Cache (Maybe v)
    In the first argument of `(.)', namely `state'
    In the expression: state . lookup
cabal: Error: some packages failed to install:
lamdu-0.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by Peaker** [comment]
Can you try with a more modern GHC?
