### ISSUE TITLE
Make fails on aeson dependencies issue.

### ISSUE THREAD

**Issue by ttyerlsol** [Peaker/lamdu#26]
Building on MacOSX Maverick with a clean install of GHC. After "cabal install aeson" and the rest of the dependencies I did a "make". Unfortunately "make" failed with the following message:

<command line>: cannot satisfy -package-id aeson-0.8.0.2-0a45c62392101b292e476335cf17659d:
    aeson-0.8.0.2-0a45c62392101b292e476335cf17659d is unusable due to missing or recursive dependencies:
      attoparsec-0.12.1.2-4234caf5378e4a4ebcf5fec65d43ea74 hashable-1.2.2.0-b7cf90008a40abec30f029373a00f9ad scientific-0.3.3.3-5c2a6b6e292891f73ca23601e08aa268 unordered-containers-0.2.5.1-28a4ce84977ab114e54414ac83a93a7f

**Comment by Peaker** [comment]
Try: cabal install --only-dependencies
