### ISSUE TITLE
Issue compiling Lamdu.Font

### ISSUE THREAD

**Issue by Ivanknmk** [Peaker/lamdu#29]
I have tried with graphics-drawingcombinators v1.5.0.3, v1.5.0.2 and v1.5 and I'm still getting this issue:

[ 82 of 120] Compiling Lamdu.Font       ( Lamdu/Font.hs, dist/build/lamdu/lamdu-tmp/Lamdu/Font.o )

Lamdu/Font.hs:19:9: Not in scope: ‘Draw.withFont’
cabal: Error: some packages failed to install:
lamdu-ide-0.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by rvion** [comment]
It would be great to have lamdu build with https://github.com/commercialhaskell/stack

**Comment by yairchu** [comment]
Hi, I made some pull request to graphics-drawingcombinators, but until they are processed, the repo to use with lamdu is https://github.com/yairchu/graphics-drawingcombinators.
The existing graphics-drawingcombinators causes crashes in some cases when using fonts and multi-threading..

**Comment by Ivanknmk** [comment]
Thank you very much @yairchu ! It's working now.
