### ISSUE TITLE
Can't write characters using AltGr

### ISSUE THREAD

**Issue by mekeor** [Peaker/lamdu#3]
Hi.

I'm using the german keyboard-layout. We have a modifier key called AltGr (https://en.wikipedia.org/wiki/Alt_Gr) which we need to type [, ], {, }, and \. But in Bottle, it doesn't work, that is, I can't write those characters. I don't get an error or any message or so either, it just doesn't write the character down.

Cheers

**Comment by Peaker** [comment]
@mekeor Is this still a problem?
