### ISSUE TITLE
reference submodules with https:// vs git@

### ISSUE THREAD

**Issue by rvion** [Peaker/lamdu#31]
fetching submodules is more complex when submodules are defined with "git@" instead of "https://"

1. If github has never been contacted before (it could be the case for CI, newly created docker containers, etc.), you have a yes/no question to answer manually
  ```
  The authenticity of host 'github.com (192.30.252.129)' can't be established.
  RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
  Are you sure you want to continue connecting (yes/no)? yes``
  ```

2. If you have no ssh key setup, operation fail anyway with
  ```
  Permission denied (publickey).
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  Clone of 'git@github.com:Peaker/Algorithm-W-Step-By-Step.git' into submodule path 'submodules/AlgoW' failed
  ```

**I'm not asking submodule definition to change from git to https**. It's more an open statement waiting for tips and tricks to smooth newcomers installation :)

**Comment by Peaker** [comment]
It's probably a reasonable change to https, and manually add/edit git remotes when you want to edit the submodules directly.
