### ISSUE TITLE
Is code runnable, and if so it should be more obvious of how to.

### ISSUE THREAD

**Issue by NightRa** [Peaker/lamdu#8]
Is code runnable, and if so it should be more obvious of how to.

**Comment by flip111** [comment]
I was also wondering how to run and save code. But this is not possible? So it's not possible to produce a real program with this??? :(

**Comment by Peaker** [comment]
Running code? Who does that? :-)

Kidding aside, we don't have it yet, but it'll be obvious when we do!

Thanks!

**Comment by alanz** [comment]
Looking forward to lamdu written in lamdu ...

**Comment by yairchu** [comment]
there is some relevant recent progress :)

![screen shot 2015-06-18 at 1 40 15 am](https://cloud.githubusercontent.com/assets/97606/8231092/9e5d1b64-15ce-11e5-9db7-37efecbc6c80.png)

**Comment by flip111** [comment]
excuse my unknowingness, but what is there to see on the picture and why is it relevant?

**Comment by Peaker** [comment]
@flip111 The white-text annotations you see underneath each sub-expression are evaluation results.  i.e: Lamdu is running the code.

**Comment by flip111** [comment]
Can a binary executable be made? Similar to normal haskell programs compiled with GHC?

**Comment by Peaker** [comment]
Not yet, it isn't a priority - as realistic programs you'd want to compile have other fundamental blockers to resolve first.

**Comment by NightRa** [comment]
@Peaker This is definitely awesome.
Now we can follow the evaluation of code!
An additional definitely useful thing would be being able to expand calls to see how they are evaluated too. (such as the recursive call in this example)

**Comment by yairchu** [comment]
@NightRa you can see the recursive calls by navigating to the arrow under largestPrimeH's parameters and browse different executions/scopes. Additionally we'll have a jump-to-call feature at some point
